services:
  - type: web
    name: wallz-demo
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_VERSION
        value: "20"
